CREATE TABLE IF NOT EXISTS sec_report_processing
(
    accessionNumber,
    formType,
    filingDate,
    filingDay,
    filingMonth,
    filingYear,
    cikNumber,
    xbrlInsUrl,
    insSize,
    xbrlPreUrl,
    preSize,
    xmlPreFile,
    preParseDate,
    preParseState,
    csvPreFile,
    xmlNumFile,
    numParseDate,
    numParseState,
    csvNumFile,
    dailyZipFile,
    processZipDate,
    fiscalYearEnd,
    PRIMARY KEY (accessionNumber)
)
